### ISSUE TITLE
Question: Is it possible to use a binary_sensor Class presence with this integration

### ISSUE THREAD

**Issue by j54j6** [pnbruckner/ha-composite-tracker#27]
Hey,

I'm a newbie to Homeassistant and didn't found any problems like mine on google so hope you can help me :)

I wan't to integrate a wifi state compared with the companion App in one device tracker. For this I've created a binary sensor with the HACS Integration eap225 (Link: https://github.com/roger1233/TPLinkEAP225-Home-assistant-custom-component).
This is working without any problems but if I want to give the state to the Composite device tracker It wont work even if I rejoin my wifi to trigger the devicetracker listener...

I've created the following device tracker:
EAP225 integration in configuration.yml

```
binary_sensor:
  - platform: eap225
    name: binary_sensor.justin_phone_in_wifi
    mac: 64:a2:00:71:a2:4c
```

device_tracker
```
device_tracker:
  - platform: composite
    name: me
    time_as: device_or_local
    entity_id:
      - binary_sensor.justin_phone_in_wifi
```

I've also had an entry in the knowndevices.yaml with track:true but this doesnt work either...
If I also add the companion App to the tracker it work well (for the companion App) but the binary sensor is still be ignored...
The Homeassistant log doesn*t include any relevant information... So I think it is basicly correct configured.

Hope you can help me :) - and thank you for this great integration ^^

j54j6

**Comment by pnbruckner** [comment]
What is the entity ID of the binary sensor? Based on your config above and a brief review of the eap225 code, I'm guessing it is _not_ `binary_sensor.justin_phone_in_wifi`. Please look on the STATES tab of the Developer Tools page to get the exact entity ID. I'm actually guessing you should change the config of the binary sensor to:
```yaml
binary_sensor:
  - platform: eap225
    name: justin_phone_in_wifi
    mac: 64:a2:00:71:a2:4c
```
Notice the difference in the `name` option.

In any case, you must configure the composite device tracker to use the _exact_ entity ID of the binary sensor.
