### ISSUE TITLE
Generate a virtual "Family" Sensor just for presence at home

### ISSUE THREAD

**Issue by Kilowatt-W** [pnbruckner/ha-composite-tracker#30]
Hi,

would it be possible to create a composite family presence Sensor that only gets the status home or away depending on the other composite sensors for my family-members ? at the momet the family sensor gets the latest update and not just home or nor ?

Would it possible to make some zones ignorable like in the proximity sensor ?

    ignored_zones:
      - "me @ Vienna"
      - "me @ Salbzurg"

Greetings
Kilowatt

**Comment by pnbruckner** [comment]
I would think all those requirements could easily be accomplished by a template sensor. Actually, probably the easiest way to do it is with an [Old style group](https://www.home-assistant.io/integrations/group/#old-style-groups), such as:
```yaml
group:
  family:
    name: Family
    entities:
      - device_tracker.me
      - device_tracker.you
```
This will create `group.family`, whose state will be `home` (aka Home) whenever any of the specified device trackers are `home`, and `not_home` (aka Away) when all of the specified device trackers are not `home` (i.e., either `not_home` or in any zone _other than_ the Home zone.)

Personally, this is what I do (where each of the `device_tracker` entities in the group are created using this composite custom integration):
```yaml
group:
  tracked_people:
    entities:
      - device_tracker.me
      - device_tracker.wife
      ...

sensor:
  - platform: template
    sensors:
      n_people_home:
        unit_of_measurement: Persons
        value_template: >
          {{ expand('group.tracked_people')
             |selectattr('state','eq','home')|list|count }}
```
