### ISSUE TITLE
Feature Request: Zone Prioritization

### ISSUE THREAD

**Issue by leoherzog** [pnbruckner/ha-composite-tracker#33]
Hi! Great add-on, thanks for making it.

It'd be nice if, when any of the entities attached to a composite tracker were detected outside of specified zones, then those entities take priority.

Said another way, it'd be nice if there was a

```yaml
device_tracker:
- platform: composite
  name: me
  time_as: device_or_local
  require_movement: true
++low_priority_zones: Home, Park
  entity_id:
    - device_tracker.phone
    - device_tracker.keys
    - device_tracker.wallet
    - device_tracker.backpack
```

where `low_priority_zones` was a list of Zones that was only registered as the current location when all four trackers were there.
