### ISSUE TITLE
GPS/Reouter combination issue

### ISSUE THREAD

**Issue by the01** [pnbruckner/ha-composite-tracker#45]
I want to combine two device tracker, lets call them "app" and "wifi". "app" is the ios companion app and "wifi" the tracker of my phone provided by the router.
If I only use the wifi trigger it works as expected- wifi switches to away -> composite_me switches to away and reverse.
However, if I include the app sensor, it stays home. Despite the composites showing "15 minutes ago" and the wifi "10 minutes ago". It even says last entity id = wifi.
Here is my config:

```yaml
composite:
  tz_finder: timezonefinder<6
  tz_finder_class: TimezoneFinderL
  default_options:
    time_as: device_or_local
    require_movement: true
  
  trackers:
    - name: Me
      id: composite_me
      require_movement: true
      entity_id:
        - device_tracker.wifi
        - device_tracker.app
```
Shouldn't it switch to away or am I missing something?
(HA OS, installed via HACS)

**Comment by the01** [comment]
Just checked again, at the moment it just ignores the "wifi" (last_id still "app" event though there is a more recent update from "wifi")

**Comment by pnbruckner** [comment]
First, sorry for taking so long to get back to you. It's been a bit hectic lately.

> However, if I include the app sensor, it stays home. Despite the composites showing "15 minutes ago" and the wifi "10 minutes ago". It even says last entity id = wifi.
> Shouldn't it switch to away or am I missing something?

If you haven't already, please read [Watched device notes](https://github.com/pnbruckner/ha-composite-tracker#watched-device-notes). It explains why it is behaving as you have observed. It is behaving normally given your configuration.

As far as it saying the last entity id = wifi, that's because that is the entity that changed the composite to home (in that case.)

If you want the wifi entity to be able to change the composite to away, then you need to change your configuration. See `all_states` under [Entity Dictionary](https://github.com/pnbruckner/ha-composite-tracker#entity-dictionary). E.g., change you config to this:

```yaml
    - name: Me
      id: composite_me
      require_movement: true
      entity_id:
        - entity: device_tracker.wifi
          all_states: true
        - device_tracker.app
```
