### ISSUE TITLE
Home Assistant 2023.7.2 results in invalid config

### ISSUE THREAD

**Issue by UPEngineer** [pnbruckner/ha-composite-tracker#48]
I have had composite installed for quite some time. Worked in HA 2023.7.1. Just updated to 2023.7.2 and now composite integration will not load.

I get this in my notifications:

![image](https://github.com/pnbruckner/ha-composite-tracker/assets/379835/29d4ecbe-3b15-4fae-8398-588ef298173a)

This is my composite configuration in configuration.yaml

```
composite:
  trackers:
    - name: scott_composite
      time_as: device_or_local
      entity_id:
        - device_tracker.scott_alexander
```

Any ideas to try?

Thanks,

Scott
