### ISSUE TITLE
Device position not set

### ISSUE THREAD

**Issue by kalon33** [pnbruckner/ha-composite-tracker#52]
I have a device that appear in HA map but is not a device_tracker object (it is a sensor, sensor.trackit_child). Is has the following attributes:

![Capture d’écran du 2023-12-20 15-42-45](https://github.com/pnbruckner/ha-composite-tracker/assets/460731/e6083dff-03e1-4720-b449-6a633424735e)
  
How can I use it in ha-composite-tracker to be able to use it as a device_tracker ?

Currently I set up this:

```
composite:
  trackers:
    - name: Child
      time_as: device_or_local
      entity_id:
        - entity: device_tracker.composite_child
          use_picture: true
        - sensor.trackit_child
```

But position is still set as unknown.
   
Thanks for your help.
