### ISSUE TITLE
Integration needs a reload when entity becomes unavailable

### ISSUE THREAD

**Issue by TroLoos** [pnbruckner/ha-composite-tracker#58]
Hi, first of all - I love the idea of this integration, I really do. Actually, I've been hoping it could become another layer of resilience for my home setup. Here's what is my current issue.

I want to use Composite Tracker to diversify home/not_home status based on more than one entity so that if one of them becomes unavailable, the status would be still reported correctly.

My current sample configuration:
```
composite:
  default_options:
    require_movement: false
  trackers:
    - name: Karol
      id: karol
      entity_id:
        - entity: device_tracker.karol_s_iphone
        - entity: binary_sensor.karol_s_iphone_wifi_at_home
```
device_tracker.karol_s_iphone - comes from Unifi integration
binary_sensor.karol_s_iphone_wifi_at_home - comes from template sensor and is update when HA companion app connects/disconnects to/from my home WiFi.

The problem is that when I disable Unifi integration / device_tracker.karol_s_iphone becomes unavailable (there are some issues ongoing with current firmware when such things happen randomly and quite often), Composite Tracker stops reacting to changes of tracker that is still available / binary_sensor.karol_s_iphone_wifi_at_home.

Are my observations correct? Would it be complicated to add logic that skips the entities that are unavailable?

**Comment by pnbruckner** [comment]
Composite already ignores `unavailable` and `unknown` states. When this happens, it is effectively remembering the last "good" state (i.e., before it became unavailable.) So, for the router-based tracker, it's remembering it is home.

By default, composite has to determine if it should use new states for non-GPS inputs (e.g., router-based trackers & binary sensors.) It always uses their state when they change to "home." However, when they change to not "home", it gets a bit complicated. Suffice it to say, the default behavior, in your scenario. means the binary sensor changing to off (while the router-based tracker is unavailable) will _not_ cause the composite to change to not "home."

To solve your problem, I would suggest enabling `all_states` for the binary sensor. I.e.,:
```yaml
composite:
  default_options:
    require_movement: false
  trackers:
    - name: Karol
      id: karol
      entity_id:
        - device_tracker.karol_s_iphone
        - entity: binary_sensor.karol_s_iphone_wifi_at_home
          all_states: true
```
Now the composite will change to not "home" when the binary sensor goes to "off". The downside is that this will always happen, even when the router-based tracker is "home" (i.e., not unavailable and indicating home.) But, maybe given your situation, this could work.
