### ISSUE TITLE
Notify no longer interacting with device tracker.

### ISSUE THREAD

**Issue by vaemarr** [pnbruckner/ha-composite-tracker#70]
I have an automation, it is split into 2x sub-routines (actions), that do the following:

First Action:

```
variables:
  target: |
    {% set x = trigger.to_state.attributes.source %} {{ states[x].object_id }}
alias: Sets the target of the notification to the person who triggered the event.
```
Second Action:

```
service: notify.mobile_app_{{ target }}
data:
  title: Shopping List
  message: >-
    {{ trigger.to_state.attributes.friendly_name }}, please review items that
    are needing purchase. Check them off when done.
  data:
    group: shopping-notification-group
    channel: Shopping
    notification_icon: mdi:cart
    color: "#A6FF96"
    clickAction: /lovelace-mushroom/house-mobile
    subtitle: Items are needed!
    car_ui: true
alias: Dispatch notification to person who entered Shopping Precinct
```

I am now, as of latest core update, getting the following. See attached.

I believe there were tracker changes in the latest update but as I am not a experienced coder I am uncertain if they are related.

Here are my details:

Core
2024.4.3
Supervisor
2024.04.0
Operating System
11.5
Frontend
20240404.2

![Screen Shot 2024-04-21 at 8 53 51 pm](https://github.com/pnbruckner/ha-composite-tracker/assets/24642114/a70bef56-65ec-4529-be3c-c6b2be045cf6)
