### ISSUE TITLE
time_as warning 

### ISSUE THREAD

**Issue by ausfas** [pnbruckner/ha-composite-tracker#77]
I'm getting this warning in the logs:
```
This error originated from a custom integration.

Logger: custom_components.composite
Source: custom_components/composite/__init__.py:149
integration: Composite (documentation, issues)
First occurred: 11:48:14 AM (1 occurrences)
Last logged: 11:48:14 AM
Your composite configuration contains options that are no longer supported: time_as; Please remove them
```

**Comment by pnbruckner** [comment]
Ok. The warning is clear. You're using a feature that is no longer supported, so you should remove it from your configuration. Have you read the README.md documentation?

**Comment by ausfas** [comment]
Sorry, I didn't realise the configuration files still has entries.
However, now I have made the changes as listed in your notes, where entities_id has been replaced with entities, making this change breaks the integration. Can you please advise if entities_id is to be replace with entities or not ?

'The entity_id attribute has been changed to entities. entity_id did not show up in the attribute list in the UI.'
```
Logger: homeassistant.config
Source: config.py:1327
First occurred: 12:16:36 PM (1 occurrences)
Last logged: 12:16:36 PM
Invalid config for 'composite' at packages/integrations/device_tracker.yaml, line 25: required key 'entity_id' not provided, please check the docs at https://github.com/pnbruckner/ha-composite-tracker/blob/3.4.2/README.md Invalid config for 'composite' at packages/integrations/device_tracker.yaml, line 28: 'entities' is an invalid option for 'composite', check: composite->trackers->0->entities, please check the docs at https://github.com/pnbruckner/ha-composite-tracker/blob/3.4.2/README.md
```
```
composite:
  default_options:
    require_movement: false
#    driving_speed: 15
  trackers:
    - name: Me
      #time_as: local
      entities:
        - entity: device_tracker.yy
          use_picture: true
        - device_tracker.pixel_8_pro
        - entity: binary_sensor.pixel_8_pro_wifi
          all_states: false
    - name: Wife
      require_movement: false
      entities:
        - entity: device_tracker.xx
          use_picture: true
        - device_tracker.xx_iphone
        - entity: binary_sensor.xx_iphone_wifi
          all_states: false
```
